[agentwatch]
homePath   = $SPLUNK_DB/agentwatch/db
coldPath   = $SPLUNK_DB/agentwatch/colddb
thawedPath = $SPLUNK_DB/agentwatch/thaweddb
maxDataSize = auto_high_volume
frozenTimePeriodInSecs = 2592000
